### ISSUE TITLE
Add user endpoint 

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#105]
#### Proposed solution
Add endpoints to save user data, especially folders created by user

#### DoD (Definition of Done)
User endpoint is there with POST, GET, PATCH, PUT (maybe DELETE if needed)

#### Testing
at least peer to peer, hopefully integration tests also

**Comment by blankdots** [comment]
user object could look like:
```{id: "something", 
drafts: [1,2,3],
folders: [1,2,3]}
```

also what would `PUT`do as we are using it with the `replace` strategy and `PATCH` for updates ?
