### ISSUE TITLE
Add connections between users and folders

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#106]
#### Proposed solution
For easy db queries, user docs should contain list of folders user has created and each folder should probably also contain info about the user who created the folder.

Also `get_folders` in handlers.py should return list of folders by user / somehow restrict users from browsing folders created by other people.

#### DoD (Definition of Done)
It's easy to query for users folders

#### Testing
peer to peer, integration, unit

**Comment by blankdots** [comment]
> somehow restrict users from browsing folders created by other people

i think when processing any request we should see if user is authenticated and after that when checking a e.g. object resource check if the user has that resource in its objects, folders etc and then show it.

this task should come after: `/users` #105

**Comment by csc-jm** [comment]
Regarding `get_folders` endpoint for user specific folders in `handlers.py`, a better way to achieve this would be to check the user logged in the session eg. from cookies. This functionality has not been implemented yet, so this issue can be delayed for now.
