### ISSUE TITLE
Add functionality to export objects from database back into XML

### ISSUE THREAD

**Issue by csc-jm-zz** [CSCfi/metadata-submitter#132]
#### Proposed solution

A feature was requested that metadata objects could be exported from the database back into XML files, especially if the object was filled and submitted through a form. Converting a JSON object back into XML perfectly requires a lot and thus, this may be a very difficult task.

#### DoD (Definition of Done)

Endpoint is implemented that gets a specific object from the database and returns it as an XML file.

#### Testing

Unit and integration tests at least

**Comment by csc-felipe** [comment]
XML to JSON is a lossy operation, and we might not be able to implement this accurately.
