### ISSUE TITLE
Add possibility to add custom schemas to application

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#17]
#### Proposed solution

In MVP version, all incoming data is validated against predefined XSD schemas (available in [ENA's repository](https://github.com/enasequence/schema). It should be also possible to add custom schemas, maybe grouped by users/organisations? 

During implementation of this feature, relationship between schemas and database should probably be thinked through. Currently all schemas are just plain files in source code.

#### DoD (Definition of Done)
- Users can submit new schemas
- Users can validate their metadata files against their schemas

#### Testing
- unit and integration tests can be added, mongomock (https://github.com/mongomock/mongomock) can be used for database mocking

**Comment by csc-felipe** [comment]
It's unsure we need custom schemas. Let's go back to this if we actually need it.
