### ISSUE TITLE
Support connecting to a MongoDB that requires TLS certificates

### ISSUE THREAD

**Issue by jbygdell** [CSCfi/metadata-submitter#179]
#### Proposed solution

Add functionality to configure the MongoDB URI with TLS options
```
&tls=true&tlsCAFile=<PATH/TO/CAFILE>&tlsCertificateKeyFile<PATH/TO/CERTIFICATE/FILE>
```
if configured for separate certificate and private key files the private key option is also needed:
```
&tlsPrivateKeyFile<PATH/TO/CERTIFICATE-KEY/FILE>
```

#### DoD (Definition of Done)

Can connect to a MongoDB server that requires presentation of TLS certificates

**Comment by pontus** [comment]
Fixed by #186.
