### ISSUE TITLE
Add possibility to create PUT and PATCH requests to object recourse uris

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#21]
#### Proposed solution
It should be possible to update metadata objects fully or partially. Make it possible to update objects via /objects/<schema>/<accessionId> and via /<schema/<accessionId> (redirection). 

#### DoD (Definition of Done)
- Objects can be updates via endpoints

#### Testing
- Test with unit tests

**Comment by otahontas** [comment]
We need to think, whether this should be actually possible at all. 

Some rproblems that might happen:
- XMLs can't be just partially updated in database (that's hard)
- if user updates JSON that has been generated from XML, JSON and XML are not in-sync. How to prevent this?

**Comment by blankdots** [comment]
partial (`patch`) upload should not be possible with XML, we will only do that to JSON
replace (`put`) I think should be the same, however I do see the need for it in some cases, where the XML has typo and someone corrects it.
