### ISSUE TITLE
Implement RESTful versions of metadata action related to study publishing

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#23]
#### Proposed solution
[ENAs programmatic submission api ](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html)supports following actions related to study publishing:
- **release** for making study public immediately
- **hold** for setting study hold (=release) date for non-public study
- **suppress** for temporarily hiding a released study
- **cancel** for cancelling/removing non-released study
- **kill** for cancelling/removing released study

Actions could be implemented with PATCH requests to /objects/study/<accessionId>, with relevant provided in body.

Corresponding actions should be implented later in frontend as well. 

#### DoD (Definition of Done)
- It's possible to change study publish status and date

#### Testing
- Unit & integration tests

**Comment by blankdots** [comment]
*hold* and *suppress* mean we don't show them to the public of we flag them so that they are not *released*

**Comment by blankdots** [comment]
Considering the current workflow of drafts objects and actual objects, we consider the drafts in an intermediate state before release and once a user publishes them in the ui to objects they are final.

**Comment by blankdots** [comment]
`folders` have a https://github.com/CSCfi/metadata-submitter/blob/master/metadata_backend/helpers/schemas/folders.json#L21 `published` key we can design the API against that if we don't need further granularity on publishing specific objects.
