### ISSUE TITLE
enable search by name and date in folders

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter#280]
#### Description

As a user that has many folders, drafts and template i would need to filter them so i can find what i am looking for.

`dateCreated` key already exists in folder but maybe this might need some indexes created in mongodb so that folders can be searched by name (text search)

Related to issue CSCfi/metadata-submitter-frontend/issues/423

#### DoD (Definition of Done)

user is able to filter by name and by date created

#### Testing

unit and integration testing

**Comment by blankdots** [comment]
for dateCreated users might want to search for:
- year
- year and moth
- year, month and day

**Comment by genie9** [comment]
Accidentally conversation held in https://github.com/CSCfi/metadata-submitter-frontend/issues/423#issuecomment-987906669:

@genie9 i assume we are talking about this backend issue CSCfi/metadata-submitter/issues/280

    @blankdots Some questions have arisen during the implementation of folder filtering by name:

    1. Should there be an additional field for searching `text_name` separating folder name by delimiters?
       
       * discussed in RC => yes

true, but that is an implementation detail.

    2. Is it good enough to search by full string matching with text search (indexed)?

yes, text search should be it to take advantage of indexing, we will not do regex. Simple (text) search, we will do, no need to do anything fancy like elastic search does.

    3. Should we implement regex with ^-prefix-  so we could use partial and also indexed search?
       
       * discussed in RC => 2 is chosen

No regex please, it is not required for this use case.

    4. Would name filtering be using only one word, not an array of words?

based on this, if there are multiple words https://docs.mongodb.com/manual/text-search/#-text-operator will create an OR so we can get as many words as needed

    5. Should `description`-field be included in the search (indexed)? How long are descriptions usually and would it mess filtering by name? (Asking because Stefan's example included `description`-field in indexing)

This I am not 100% sure, but I would leave out, as descriptions can often take the form of an abstract. If we get request to do it then we will add it with another issue.

    6. Should the new field `text_name` be shown in the query results?

No. that is internal
