### ISSUE TITLE
Enable language support for JSON forms

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter#283]
#### Description
JSO

Related issue: CSCfi/metadata-submitter-frontend/issues/490

Enable support in the backend to allow different languages to be selected with e.g. `?lang=en` parameter, when retrieving a JSON schema.
Default will be English if language is not found.

#### DoD (Definition of Done)

JSON form support language

#### Testing

Unit and integration testing

**Comment by csc-felipe** [comment]
@jaakkocsc, can we close this?
