### ISSUE TITLE
Decide what to implement from submission.xml based submissions

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#34]
#### Description
Programmatic submissions in ENA system can be done with submission.xml file: https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html. Currently we have just very basic support for adding submission with "ADD" action in submission.xml. This is done through /submit. 

I think at some point we need to decide whether to implement some of the submission.xml actions. Many of those correspond to REST-api methods and can be probably just mapped internally in handlers.py module or something similar.

**Comment by blankdots** [comment]
we need to implement:
- ADD
- MODIFY
- VALIDATE
- RELEASE

I think we can skip the rest.

**Comment by blankdots** [comment]
We can drop `RELEASE` as we are doing release in a different manner.
