### ISSUE TITLE
Move metax info from object to folder on publish

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#367]
On folder publishing study and dataset objects' metax info is moved inside folder's corresponding metadataObjects entry

EDIT:
There is no need to move metax identifier to the folder. On folder publishing study and datasets data with findable metax url is updated to folder's extra info.

**Comment by blankdots** [comment]
we actually don't need to move anything to `metadataObjects`  we only need from metax the `url` to be used by Datacite DOIs to be discoverable. e.g. `https://etsin.fairdata.fi/dataset/{metax_identifier}` which we do (partly) already

**Comment by blankdots** [comment]
this should have been done with #369
