### ISSUE TITLE
Investigate use of submission patch and refactor it to meet the needs

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#430]
#### Description
The use of endpoint for patching submission has changed radically during a few code updates. Currently, it is probably used to only update the submission's `name` and `description` but it needs to be investigated. If this is the case, then the patching function should be minimized to accept only those fields as JSON and no extra db-related information.
Current request body for the call:
` [{"op": "replace", "path": "/name", "value": "test2"}]`
Expected request body for the call:
`{"name": "test2"}`

#### DoD (Definition of Done)
Call to patch `submission/<submission_id>` will update only submission's `name` and `description` with simple JSON string.
The frontend has been adapted with this update.
Tests and documentation are updated with changes if needed.

#### Testing
Integration tests both on the front and the backend

**Comment by csc-felipe** [comment]
Replaced **folder** with **submission**.

**Comment by csc-felipe** [comment]
The other endpoints still support PATCH with the same syntax. Should we only restrict which fields in submission can be updated with PATCH, or also refactor other PATCH endpoints to function similarly, without the JSON:patch syntax?

I think it's worse UX that submission PATCH endpoint has different format than the other PATCH endpoints.

**Comment by csc-felipe** [comment]
This change also means that some possible use cases would be removed, for e.g., what's now in integration tests: https://github.com/CSCfi/metadata-submitter/blob/53c60c7e6242ff3793427ee2f9edc7895bcf70f7/tests/integration/run_tests.py#L1606=
