### ISSUE TITLE
Make integration tests idempotent

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#448]
#### Proposed solution

Currently, the integration tests modify the DB state, and depend on each other.

It makes it difficult to develop new tests, as DB must be cleared manually after every run.

#### DoD (Definition of Done)

- Integration tests can be run multiple times in a row.
- Failing tests leave the environment in a clean state.

#### Testing

Run integration tests multiple times in the same environment, and observe the same output / result.

**Comment by csc-felipe** [comment]
Perhaps we could use [pytest with fixtures for this](https://docs.pytest.org/en/6.2.x/fixture.html#fixtures).

**Comment by blankdots** [comment]
> Currently, the integration tests modify the DB state, and depend on each other.

could we get more info on this, as i remember they were kind self contained each testing a different thing and creating its own fixtures?

they do leave a lot of `submissions` just to identify there aren't any interactions between each `submission` data as we have had concurrency issues in the past.

the solution done by #477 should have fixed this ?

**Comment by csc-felipe** [comment]
I think that PR did the most important part, which was to be able to re-run tests without intermediate commands. It does still bother me, that the development DB is the same as the test DB though.

What I was having in mind next was to migrate the tests to use Pytest and fixtures. I think it will allow to more easily create certain kinds of tests, for e.g. no metax service running, and such. Should we have a chat about this?

**Comment by csc-felipe** [comment]
#570 was a step forward, but I would still like to 
- split integration tests into multiple files,
- be able to control running services from the code (to test for when a service is down, for example).
