### ISSUE TITLE
Return XML fileSize under tags

### ISSUE THREAD

**Issue by hannyle** [CSCfi/metadata-submitter#449]
#### Proposed solution

Currently when submitting a XML file, the submitted file is under **_submission's metadataObjects_** and it receives the value of `tags` including: `{ displayTitle, fileName, submissionType }`.
The new implementation of front-end also needs to show the submitted XML file's size.

#### DoD (Definition of Done)
Submitted XML `fileSize` is returned together with `{ displayTitle, fileName, submissionType }` under `submission>metadataObjects>tags` 

#### Testing
Unit/Integration testing

**Comment by genie9** [comment]
Discussed with @ainoc that this information is irrelevant
