### ISSUE TITLE
Find out how are errors returned by metax, and process them.

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#461]
#### Proposed solution

This is a follow-up from #453.
When receiving errors from Metax, they could be better formatted, instead of just passing them forward.

#### DoD (Definition of Done)

Error messages from Metax are included in response in a better format.

**Comment by genie9** [comment]
The error message coming from metax is documented in metax mock code API https://github.com/CSCfi/metadata-submitter/blob/e8f9ec4181f5c9b03c6f092b423652316e60c418/tests/integration/mock_metax_api.py#L19
We could add `metax` suffix for the error

**Comment by csc-felipe** [comment]
Following service handlers implementation, I think error messages are already properly processed. We can open a new ticket if it looks like metax error messages are not being properly processed.
