### ISSUE TITLE
Publishing Submission without doi_info returns HTTP500

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#464]
#### Describe the bug
When publishing Submission without doi_info HTTP500 is returned. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Crete folder in metadata submitter API
2. Try to publish the folder
3. See error HTTP500 KeyError: 'doiInfo'

#### Expected behavior

Backend should return HTTPBadRequest on missing doi_info and message that it's missing.

**Comment by csc-felipe** [comment]
Duplicate of #412
