### ISSUE TITLE
Publishing without submitted Study returms HTTP500

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#465]
#### Describe the bug
When publishing a Submission without a Study HTTP500 is returned. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Crete folder in metadata submitter API
2. Submit DOI (datasite metadata)
3. Try to publish the folder
4. See error HTTP500,  KeyError: 'id'

#### Expected behavior

Backend should return HTTPBadRequest on missing Study and message to that it's missing.

**Comment by csc-felipe** [comment]
Duplicate of #422
