### ISSUE TITLE
Make using of discovery service (METAX) optional

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#467]
#### Description

We have been implementing integration with the FAIRDATA Metax service as part of the standard workflow for submission publishing.
Now we have a need to make that integration optional as BIGPICTURE submissions won't be using FAIRDATA as a discovery service.
The proposition is to add an environment variable that would indicate what workflow will be used. This env var will probably be used also for schema validation so it could be something like `SUBMIT_WORKFLOW` and value `bigpicture`. 
As for FAIRDATA `SUBMIT_WORKFLOW` value could be `standard` as it is considered a standard use case.

#### DoD (Definition of Done)

When submitting metadata and publishing submission with env var `SUBMIT_WORKFLOW: bigpicture` submissions' metadata is not sent to Metax.

#### Testing

Not yet decided, but coming soon...

**Comment by csc-felipe** [comment]
@genie9, can we actually do this?

The publication URL seems to be DOI url + metax ID 
https://github.com/CSCfi/metadata-submitter/blob/be0002cee252a6babf8e8169398bc2329eedcdac/metadata_backend/api/handlers/submission.py#L49
