### ISSUE TITLE
Authentication for API users

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#468]
#### Description

There's a need for authentication to be implemented for API users. 
More descriptions coming soon...
   
#### DoD (Definition of Done)

A metadata submitter API user can be authenticated through API so that he can submit his metadata through an API.

#### Testing

Coming soon...

**Comment by csc-felipe** [comment]
We would need to restrict access so that users cannot create new users, or have permissions we were not expecting them to.
