### ISSUE TITLE
Redefine better error structure for front-end

### ISSUE THREAD

**Issue by csc-jm** [CSCfi/metadata-submitter#48]
#### Proposed solution
Regarding errors messages being displayed in the front-end, the error responses produced by the back-end might need to be restructured.

**Comment by otahontas** [comment]
we could maybe have: 
{error: "short error reason blahblah",
(if needed) details: "more details such as report from validation process"}

**Comment by otahontas** [comment]
Refactoring should be done against new openapi specs. Following things need to be changed:
- fix all the errors to follow same json format
- add better error details for validation responses when validation doesn't go through
