### ISSUE TITLE
Fix api responses to be more human friendly

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#49]
#### Proposed solution
Stuff that needs to be fixed:
- date result (now just python datetime dump)
- answers from /submit -endpoint should contain all generated accessionIds
- schemas should have title, detail and url in response json
- remove internal _id from api responses
- add createdDate and updatedDate

Parsing-process related stuff that needs to be fixed:
- acstract, title, descriptions have newline characters and <>-characters. 
- attribute-keys. Should be possible to remove attribute-keys and elevate values behind keys one level higher.
- children-keys. Conversion process now creates children-key and list of children. Maybe try to elevate these one step higher also? 

#### DoD (Definition of Done)
- Api responses look more human friendly

#### Testing
- Unit testing

**Comment by blankdots** [comment]
probably wait till #13  is finalised to see full list

**Comment by otahontas** [comment]
Extracted parsing process related stuff to #58, this is now solved with #56
