### ISSUE TITLE
Create EGA DAC when REMS DAC is submitted

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#532]
#### Proposed solution

Rems integration replaces the need to submit EGA DAC, but we could create the DAC EGA object automatically when a REMS DAC is created.

#### DoD (Definition of Done)

EGA DAC object is created when a REMS DAC is submitted.

**Comment by blankdots** [comment]
I think we need to get the first contact from a REMS workflows (name, email and organization), application link (REMS application link) and title of the Workflow as the DAC title in our submission
