### ISSUE TITLE
LS AAI group support

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/metadata-submitter#548]
Our group structure is based on CSC projects that come from CSC IDM. BIGPICTURE will use LS AAI instead of CSC IDM for managing group membership. Add support for managing groups(projects) from LS AAI groups also.

**Comment by teemukataja** [comment]
LS AAI design is pending, but this change probably affects fetching of the projects and user id here https://github.com/CSCfi/metadata-submitter/blob/master/metadata_backend/api/auth.py#L152-L165

**Comment by csc-felipe** [comment]
Related to #468

**Comment by csc-felipe** [comment]
Another way to do this, as suggested by @blankdots, is to allow users to create projects, which would make it so that we would also need to have user roles.
