### ISSUE TITLE
Check for dead code 😵

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#577]
#### Proposed solution

While working on #546 or #482, I noticed that some code might not be in use.

There seem to be a few tools around to check for dead code, and from my quick research, [Vulture](https://github.com/jendrikseipp/vulture) seems to be a good candidate.

While static check might give false positives, It should be investigated why the code is reported dead, and is it really not necessary, and unused?

#### Tasks
- [x] Introduce a new check for dead code
- [x] Investigate and fix each instance

#### DoD (Definition of Done)

Remove dead code from the codebase, and prevent new instances of dead code.

#### Testing

A new check should be added to `pre-commit`, `tox`, and `ci`.

**Comment by blankdots** [comment]
i went over the dead code and it seems a lot of it is the cause of a faulty rebase or rollback e.g. https://github.com/CSCfi/metadata-submitter/blob/develop/metadata_backend/api/handlers/user.py#L21
