### ISSUE TITLE
use defusedxml library

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter#73]
#### Description

xml library from python is considered unsecure

#### DoD (Definition of Done)

make use of  https://pypi.org/project/defusedxml/

#### Testing

Peer review and maybe unit tests

**Comment by otahontas** [comment]
btw apparently xmlschema-lib decided not use defusedxml, but instead some custom solutions: https://github.com/sissaschool/xmlschema/issues/167#issuecomment-583034086.

**Comment by blankdots** [comment]
apparently `xmlschema` has a way to deal with it https://github.com/sissaschool/xmlschema/blob/master/xmlschema/etree.py#L31-L35 so let us use that
