### ISSUE TITLE
Add parsing for permissions and statuses

### ISSUE THREAD

**Issue by csc-jm** [CSCfi/metadata-submitter#96]
#### Proposed solution
The `jwt_middleware()` also needs to parse permissions and statuses from ELIXIR token for GA4GH claims. Details about GA4GH AAI can be found [here](https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md) and a seemingly good implementation of this exists in the [Beacon API Server](https://github.com/CSCfi/beacon-python/blob/master/beacon_api/permissions/ga4gh.py).

#### DoD (Definition of Done)

Preferably a new module that checks the token in use for GA4GH claims, retrieves the GA4GH passports and processes them into sets of permissions that can be included with the `request["token"]` value.

#### Testing

- A mock of OAuth2 server could be in place for integration testing

**Comment by csc-jm** [comment]
Issue is directed towards this part:
https://github.com/CSCfi/metadata-submitter/blob/e611e8f3a3026387c298603fce86d9b3b7a6c54b/metadata_backend/api/middlewares.py#L92-L101

**Comment by blankdots** [comment]
This issue is not valid any more and closing in favour of #135
