### ISSUE TITLE
Add support for adding metadata object folders 

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#97]
#### Proposed solution

Users should be able to collect metadata objects into folders. Folders are mainly views to how objects are linked together, so at first we could have following:
- endpoint with crud methods for folder: 
   - /folders/ GET --> return all folders, POST --> add new
   - /folders/{folder_id} GET --> return one folder, PUT --> replace one folder, PATCH --> partially update one folder, DELETE --> delete folder
- support for folders in database

Suggestion for folder-json structure: 
```
{
  id: "Mongodb generated Id", 
  metadata_objects: [
{ "accessionId": "EGA12356", 
  "schema": "Study" }, 
{ "accessionId": "EGA12356339", 
  "schema": "Sample" }, 
{ "accessionId": "EGA12356398", 
  "schema": "Experiment" }, 
]
}
```

#### DoD (Definition of Done)
Folder endpoints are implemented 

#### Testing
Unit and integration tests

**Comment by otahontas** [comment]
This is a big issue, so feel free to break it to smaller pieces

**Comment by blankdots** [comment]
We can close the issue as most things were addressed by the PRs.
if need be we can create additional ones.
